### PR TITLE
[sanitize_html] Migrate to null safety

### PR DESCRIPTION
**Pull request by stuartmorgan**

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@jonasfj Are you the right reviewer for this?

@ditman FYI; I noticed you'll need this for maps.

**Review by jonasfj — APPROVED** [review]
r+

**Comment by stuartmorgan** [comment]
It's not clear to me what's causing the CI failures.

**Comment by jonasfj** [comment]
I think CI failures are unrelated, I'll take a look.

**Comment by jonasfj** [comment]
Merged through https://github.com/google/dart-neats/pull/104 and published to `pub.dev`

**Comment by ditman** [comment]
Thanks @stuartmorgan, @jonasfj!

**Pull request closed without merging**
